# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "OCI Compute Clusters"
stackDescription: "This stack deploys OCI clusters of Compute instances. Supported types are compute clusters and cluster networks."
description: "This stack deploys OCI clusters of Compute instances. Supported types are compute clusters and cluster networks."
schemaVersion: 1.1.0
version: "0.1.0"
locale: "en"

# URL of CIS Landing Zone logo icon used on Application Information tab.
logoUrl: "https://objectstorage.us-ashburn-1.oraclecloud.com/p/taf6kC9fSJyQDNSYbxvqxS_JsdnSu56oFZ3-1h5vI7-WfJUv77mplChopLxZPePW/n/ociateam/b/cis-landing-zone/o/landing_zone_130.png"

variableGroups:
  - title: "Cluster"
    variables:
      - "region"
      - "cluster_compartment_id"
      - "cluster_ad"
      - "cluster_name"
      - "cluster_type"

  - title: "Cluster Network Settings"
    variables:
      - "cluster_network_pool_name"
      - "cluster_network_pool_size"
      - "cluster_network_source"
      - "cluster_network_source_image_compartment_id"
      - "cluster_network_source_image_id"
      - "cluster_network_source_image_shape"
      - "cluster_network_source_instance_compartment_id"
      - "cluster_network_source_instance_id"
      - "cluster_network_vcn_compartment_id"
      - "cluster_network_vcn_id"
      - "cluster_network_subnet_id"
      - "cluster_network_ipv6_cidrs_enable"
      - "cluster_network_ipv6_cidrs"
      - "cluster_network_secondary_vnic_enable"
      - "cluster_network_secondary_vnic_name"
      - "cluster_network_secondary_vnic_vcn_compartment_id"
      - "cluster_network_secondary_vnic_vcn_id"
      - "cluster_network_secondary_vnic_subnet_id"
      - "cluster_network_secondary_vnic_ipv6_cidrs_enable"
      - "cluster_network_secondary_vnic_ipv6_cidrs"
    visible:
      eq:
        - ${cluster_type}
        - "cluster_network"

  - title: "Compute Cluster Settings"
    variables:
      - "compute_cluster_size"
      - "compute_cluster_source_image_compartment_id"
      - "compute_cluster_source_image_id"
      - "compute_cluster_source_image_shape"
      - "compute_cluster_vcn_compartment_id"
      - "compute_cluster_vcn_id"
      - "compute_cluster_subnet_id"
      - "compute_cluster_nsg_id"
    visible:
      eq:
        - ${cluster_type}
        - "compute"  

  - title: "Hidden Variables"
    visible: false
    variables:
      - "tenancy_ocid"
      - "user_ocid"
      - "fingerprint"
      - "private_key_path"
      - "private_key_password"      

variables:
  region:
    type: oci:identity:region:name
    title: "Region"
    description: "Select the region for resources deployment."
    required: true

  cluster_compartment_id:
    type: oci:identity:compartment:id
    title: "Cluster Compartment"
    description: "Select the compartment where the cluster is created."
    
  cluster_ad:
    type: oci:identity:availabilitydomain:name
    title: "Cluster Availability Domain"
    description: "Select the availability domain where the cluster is created."
    dependsOn:
      compartmentId: ${cluster_compartment_id}
  
  cluster_name:
    type: string
    title: "Cluster Name"
    description: "Enter the cluster name."
    required: true

  cluster_type:
    type: enum
    title: "Cluster Type"
    description: "Select the cluster type. Different fields are shown based on the selected type."
    required: true
    enum:
      - "cluster_network"
      - "compute" 

  cluster_network_pool_name:
    type: string
    title: "Cluster Network Pool Name"
    description: "Enter the pool name for the cluster network."
  
  cluster_network_pool_size:
    type: number
    title: "Cluster Network Pool Size"
    description: "Enter the pool size for the cluster network."

  cluster_network_source:
    type: enum
    title: "Cluster Network Source"
    description: "Select the source template for cluster network members."
    enum:
      - "image"
      - "existing_instance"  

  cluster_network_source_image_compartment_id:
    type: oci:identity:compartment:id
    title: "Cluster Network Source Image Compartment"
    description: "Select the compartment where the source image is located."
    visible:
      eq:
        - ${cluster_network_source}
        - "image"

  cluster_network_source_image_id:
    type: oci:core:image:id
    title: "Cluster Network Source Image"
    description: "Select the source image for cluster network members."
    visible:
      eq:
        - ${cluster_network_source}
        - "image"
    dependsOn:
      compartmentId: ${cluster_network_source_image_compartment_id}

  cluster_network_source_image_shape:
    type: oci:core:instanceshape:name
    title: "Cluster Network Source Image Shape"
    description: "Select the source image shape for cluster network members. The list shows all the shapes compatible with the selected image. Make sure to select a <a href='https://docs.oracle.com/en-us/iaas/Content/Compute/Tasks/managingclusternetworks.htm#supported-shapes'>shape that supports cluster networks</a>."
    dependsOn:
      compartmentId: ${cluster_network_source_image_compartment_id}
      imageId: ${cluster_network_source_image_id}
    visible:
      eq:
        - ${cluster_network_source}
        - "image"

  cluster_network_source_instance_compartment_id:
    type: oci:identity:compartment:id
    title: "Existing Source Instance Compartment"
    description: "Select the compartment where the existing source instance is located."
    visible:
      eq:
        - ${cluster_network_source}
        - "existing_instance"  

  cluster_network_source_instance_id:
    type: oci:core:instance:id
    title: "Existing Source Instance"
    description: "Select the existing source instance for cluster network members."
    visible:
      eq:
        - ${cluster_network_source}
        - "existing_instance"
    dependsOn:
      compartmentId: ${cluster_network_source_instance_compartment_id}    
  
  cluster_network_vcn_compartment_id:
    type: oci:identity:compartment:id
    title: "Cluster Network VCN Compartment"
    description: "Select the compartment where the cluster network VCN is located."

  cluster_network_vcn_id:
    type: oci:core:vcn:id
    title: "Cluster Network VCN"
    description: "Select the VCN for cluster network members."
    dependsOn:
      compartmentId: ${cluster_network_vcn_compartment_id}
  
  cluster_network_subnet_id:
    type: oci:core:subnet:id
    title: "Cluster Network Subnet"
    description: "Select the subnet for cluster network members."
    dependsOn:
      compartmentId: ${cluster_network_vcn_compartment_id}
      vcnId: ${cluster_network_vcn_id} 

  cluster_network_ipv6_cidrs_enable:
    type: boolean
    title: "Enable IPv6 CIDR blocks?"
    description: "Check to enable IPv6 CIDR blocks for the cluster network. The blocks are obtained from the selected subnet."

  cluster_network_ipv6_cidrs:
    type: array
    items:
      type: string
    uniqueItems: true
    title: "List of IPv6 CIDR Blocks"
    description: "Enter the list of IPv6 CIDR blocks for cluster network members. Type 'enter' after each entry."
    visible: cluster_network_ipv6_cidrs_enable
  
  cluster_network_secondary_vnic_enable:
    type: boolean
    title: "Enable Secondary VNIC?"
    description: "Check to enable secondary VNIC for cluster network members."  

  cluster_network_secondary_vnic_name:
    type: string
    title: "Secondary VNIC name"
    description: "Enter the secondary VNIC name."
    visible: cluster_network_secondary_vnic_enable

  cluster_network_secondary_vnic_vcn_compartment_id:
    type: oci:identity:compartment:id
    title: "Secondary VNIC VCN Compartment"
    description: "Select the compartment where the cluster VCN with secondary VNICs is located."
    visible: cluster_network_secondary_vnic_enable

  cluster_network_secondary_vnic_vcn_id:
    type: oci:core:vcn:id
    title: "Cluster VCN with Secondary VNICs"
    description: "Select the VCN with Secondary VNICs for cluster network members."
    visible: cluster_network_secondary_vnic_enable
    dependsOn:
      compartmentId: ${cluster_network_secondary_vnic_vcn_compartment_id}
  
  cluster_network_secondary_vnic_subnet_id:
    type: oci:core:subnet:id
    title: "Cluster Subnet with Secondary VNICs"
    description: "Select the subnet with Secondary VNICs for cluster network members."
    visible: cluster_network_secondary_vnic_enable
    dependsOn:
      compartmentId: ${cluster_network_secondary_vnic_vcn_compartment_id}
      vcnId: ${cluster_network_secondary_vnic_vcn_id}  

  cluster_network_secondary_vnic_ipv6_cidrs_enable:
    type: boolean
    title: "Enable IPv6 CIDR blocks for Secondary VNICs?"
    description: "Check to enable IPv6 CIDR blocks for the cluster secondary VNICs. The blocks are obtained from the selected subnet."
    visible: cluster_network_secondary_vnic_enable

  cluster_network_secondary_vnic_ipv6_cidrs:
    type: array
    items:
      type: string
    uniqueItems: true
    title: "List of IPv6 CIDR Blocks for Secondary VNICs"
    description: "Enter the list of IPv6 CIDR blocks for cluster members secondary VNICs. Type 'enter' after each entry."
    visible: cluster_network_secondary_vnic_ipv6_cidrs_enable

  compute_cluster_size:
    type: number
    title: "Compute Cluster Size"
    description: "Enter the number of instances for the Compute cluster. All instances are created with the same configuration, specified by the parameters below."
  
  compute_cluster_source_image_compartment_id:
    type: oci:identity:compartment:id
    title: "Computer Cluster Source Image Compartment"
    description: "Select the compartment where the source image for the instance members is located."

  compute_cluster_source_image_id:
    type: oci:core:image:id
    title: "Compute Cluster Source Image"
    description: "Select the source image for compute cluster members."
    dependsOn:
      compartmentId: ${compute_cluster_source_image_compartment_id}

  compute_cluster_source_image_shape:
    type: oci:core:instanceshape:name
    title: "Compute Cluster Source Image Shape"
    description: "Select the source image shape for compute cluster members."
    dependsOn:
      compartmentId: ${compute_cluster_source_image_compartment_id}
      imageId: ${compute_cluster_source_image_id}    

  compute_cluster_vcn_compartment_id:
    type: oci:identity:compartment:id
    title: "Compute Cluster VCN Compartment"
    description: "Select the VCN compartment for the compute cluster members."

  compute_cluster_vcn_id:
    type: oci:core:vcn:id
    title: "Compute Cluster VCN"
    description: "Select the VCN for the compute cluster members."
    dependsOn:
      compartmentId: ${compute_cluster_vcn_compartment_id}
  
  compute_cluster_subnet_id:
    type: oci:core:subnet:id
    title: "Compute Cluster Subnet"
    description: "Select the subnet for the compute cluster members."
    dependsOn:
      compartmentId: ${compute_cluster_vcn_compartment_id}
      vcnId: ${compute_cluster_vcn_id}   

  compute_cluster_nsg_id:
    type: oci:core:nsg:id
    title: "Compute Cluster Network Security Group (NSG)"
    description: "Select the NSG for the compute cluster members."
    dependsOn:
      compartmentId: ${compute_cluster_vcn_compartment_id}
      vcnId: ${compute_cluster_vcn_id}                
